<?xml version="1.0"?>

<robot name="arm" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:include filename="$(find kuka_youbot)/xacro/variables.xacro" />


    <link name="base">
        <visual>
            <geometry>
                <cylinder radius="${base_radius}" length="${base_length}"/>
            </geometry>
            <origin xyz="0 0 ${base_length/2}"/>
        </visual>
    </link>

    <joint name="j1" type="revolute">
            <parent link= "base"/>
            <child link="link1"/>
            <origin xyz="0 0 ${base_length}"/>
            <limit effort="100" velocity="${joint1_velocity}" lower="${joint1_min_limit}" upper="${joint1_max_limit}"/>
            <axis xyz="0 0 1"/>
    </joint>

    <link name="link1">
        <visual>
            <geometry>
                <cylinder radius="${link1_radius}" length="${link1_length}"/>
            </geometry>
            <origin xyz="0 0 ${link1_length/2}"/>
            <material name="blue">
                <color rgba="0 0 1 0.5"/>
            </material>
      0  </visual>
    </link>

    <joint name="j2" type="revolute">
        <parent link= "link1"/>
        <child link="link2"/>
        <origin xyz="0 0 ${link1_length}" rpy="-1.5702 -1.5702 0"/>
        <limit effort="100" velocity="${joint2_velocity}" lower="${joint2_min_limit}" upper="${joint2_max_limit}"/>
        <axis xyz="0 0 1"/>
    </joint>

    <link name="link2">
        <visual>
            <geometry>
                <cylinder radius="${link2_radius}" length="${link2_length}"/>
            </geometry>
            <origin xyz="${link2_length/2} 0 0" rpy="0 1.5702 0"/>
            <material name="green">
                <color rgba="0 1 0 0.5"/>
            </material>
        </visual>
    </link>
<joint name="j3" type="revolute">
        <parent link= "link2"/>
        <child link="link3"/>
        <origin xyz="${link2_length} 0 0" rpy="0 0 0"/>
        <limit effort="100" velocity="${joint3_velocity}" lower="${joint3_min_limit}" upper="${joint3_max_limit}"/>
        <axis xyz="0 0 1"/>
    </joint>

    <link name="link3">
        <visual>
            <geometry>
                <cylinder radius="${link3_radius}" length="${link3_length}"/>
            </geometry>
            <origin xyz="${link3_length/2} 0 0" rpy="0 1.5702 0"/>
            <material name="red">
                <color rgba="1 0 0 0.5"/>
            </material>
        </visual>
    </link>

    <joint name="j4" type="revolute">
        <parent link= "link3"/>
        <child link="link4"/>
        <origin xyz="${link3_length} 0 0 "/>
        <limit effort="100" velocity="${joint4_velocity}" lower="${joint4_min_limit}" upper="${joint4_max_limit}"/>
        <axis xyz="0 0 1"/>
    </joint>

    <link name="link4">
        <visual>
            <geometry>
                <cylinder radius="${link4_radius}" length="${link4_length}"/>
            </geometry>
            <origin xyz="${link4_length/2} 0 0" rpy="0 1.5702 0"/>
            <material name="blue"/>
        </visual>
    </link>

    <joint name="j5" type="revolute">
        <parent link= "link4"/>
        <child link="link5"/>
        <origin xyz="${link4_length} 0 0" rpy="0 1.5702 0"/>
        <limit effort="100" velocity="${joint5_velocity}" lower="${joint5_min_limit}" upper="${joint5_max_limit}"/>
        <axis xyz="1 0 0"/>
    </joint>

    <link name="link5">
        <visual>
            <geometry>
                <cylinder radius="${link5_radius}" length="${link5_length}"/>
            </geometry>
            <origin xyz="0 0 ${link5_length/2}" rpy="0 0 0"/>
            <material name="green"/>
        </visual>
    </link>
       <!-- Gripper base connected to link5 -->

    <joint name="gripper_joint" type="fixed">
        <parent link="link5"/>
        <child link="gripper_base"/>
        <origin xyz="0 0 ${link5_length}" rpy="0 0 1.57"/>
    </joint>

    <link name="gripper_base">
        <visual>
            <geometry>
                <box size="${gripper_base_length} ${gripper_base_width} ${gripper_base_height}"/>
            </geometry>
            <origin xyz="0 0 ${gripper_base_height/2}"/>
            <material name="gray">
                <color rgba="0.6 0.6 0.6 1.0"/>
            </material>
        </visual>
    </link>
    <!-- Left Finger -->

    <joint name="left_finger_joint" type="prismatic">
        <parent link="gripper_base"/>
        <child link="left_finger"/>
        <origin xyz="${-gripper_base_length/2} 0 ${gripper_base_height/2}"/>
        <axis xyz="1 0 0"/>
        <limit effort="10" velocity="0.01" lower="${Finger_min_limit}" upper="${Finger_max_limit}"/>
    </joint>

    <link name="left_finger">
        <visual>
            <geometry>
                <box size="${Finger_length} ${Finger_width} ${Finger_height}"/>
            </geometry>
            <origin xyz="${Finger_length/2} 0 ${Finger_height/2}"/>
            <material name="black">
                <color rgba="0 0 0 1"/>
            </material>
        </visual>
    </link>

    <!-- Right Finger -->
    <joint name="right_finger_joint" type="prismatic">
        <parent link="gripper_base"/>
        <child link="right_finger"/>
        <origin xyz="${gripper_base_length/2} 0 ${gripper_base_height/2}"/>
        <axis xyz="-1 0 0"/>
        <limit effort="10" velocity="0.01" lower="${Finger_min_limit}" upper="${Finger_max_limit}"/>
        <mimic joint="left_finger_joint" multiplier="1.0" offset="0"/>
    </joint>

    <link name="right_finger">
        <visual>
            <geometry>
                <box size="${Finger_length} ${Finger_width} ${Finger_height}"/>
            </geometry>
            <origin xyz="${-Finger_length/2} 0 ${Finger_height/2}"/>
            <material name="black"/>
        </visual>
    </link>


</robot>
